#!/bin/bash
deploy_dir="/data/deploy_root"
webroot="/data/app/wwwroot"
timestamp="$(date +%Y%m%d%H%M%S)"
. /opt/release
deploy_index_style(){
cd $deploy_dir
if [ ! -d "$deploy_dir/$1" ]
        then
                git clone git@git.ipo.com:dev1/$1.git --recursive
		cd $1
		mkdir version
        else
                echo "remove old version index,and fech newist version"
		mkdir -p $deploy_dir/$1/version
		mv $deploy_dir/$1/version /tmp/
		rm -rf $deploy_dir/$1	
		git clone git@git.ipo.com:dev1/$1.git --recursive
		mv /tmp/version $deploy_dir/$1/
fi
cd $deploy_dir/$1
version=$(cat .git/refs/heads/master)
echo "fetch index code version: $version success"
echo $version >version.txt
echo "---start sync local deploy dir to local webroot---"
rsync  -r --delete $deploy_dir/$1/ $webroot/$1/
echo "---sync local deploy dir to local webroot done---"

do_sync "$WEBS" "$webroot/$1/"
}

deploy_project(){
cd $deploy_dir
mkdir -p "$deploy_dir/$1/"
cd "$deploy_dir/$1/"
if [ $# -lt 2 ]
then
	echo "usage :deploy_project cms ga or deploy_project cms beta "
	exit
else
	if [[ "$2" == "beta_to_beta" ]]
	then
		git clone  git@git.ipo.com:dev1/$1.git $timestamp --recursive
		cd $timestamp
		git checkout -b beta origin/beta
		echo "$timestamp" > $deploy_dir/index/version/$1.beta
		version=$(cat .git/refs/heads/master)
		echo "fetch index code version: $version success"
		echo $version >version.txt
		echo "---start sync local deploy dir to local webroot---"
		rsync  -r --delete $deploy_dir/$1/$timestamp $webroot/$1/
		cp -a $deploy_dir/index/version/$1.beta  $webroot/index/version/
		do_sync "$WEBS" "$webroot/$1/$timestamp/"
		do_sync "$WEBS" "$webroot/index/version/$1.beta"
		echo "---sync local deploy dir to local webroot done---"
	elif [[ "$2" == "master_to_beta" ]]
	then
		git clone  git@git.ipo.com:dev1/$1.git $timestamp --recursive
                cd $timestamp
		echo "$timestamp" > $deploy_dir/index/version/$1.beta
		echo "$timestamp" > $deploy_dir/index/version/$1.ga
                version=$(cat .git/refs/heads/master)
                echo "fetch index code version: $version success"
                echo $version >version.txt
                echo "---start sync local deploy dir to local webroot---"
                rsync  -r --delete $deploy_dir/$1/$timestamp $webroot/$1/
		cp -a $deploy_dir/index/version/$1.beta  $webroot/index/version/
		echo "---sync local deploy dir to local webroot done---"
		do_sync "$WEBS" "$webroot/$1/$timestamp/"
		do_sync "$WEBS" "$webroot/index/version/$1.beta"
	elif [[ "$2" == "master_to_ga" ]]
	then
		if [ -f "$deploy_dir/index/version/$1.ga" ]
		then
			v="$(cat $deploy_dir/index/version/$1.ga)"
			if [ -d "$webroot/$1/$v" ]
			then
				echo "****release $1 to ga ,TimeStamp: $v ,git_version: $(cat $webroot/$1/$v/version.txt)****"
				cp -a $deploy_dir/index/version/$1.ga  $webroot/index/version/
				do_sync "$WEBS" "$webroot/index/version/$1.ga"
			else
				echo "no ga dir $v in $1"
				exit 1
			fi
		else
			echo "no $1.ga file in $deploy_dir/index/version/"
		fi
	else
		echo "there is no branch $1"
	fi
fi
}

#deploy_project file  master_to_ga
#deploy_index

if [ $# -lt 2 ]
then 
	echo "usage: ./deploy cms beta_to_beta --> ./deploy cms master_to_beta --> ./deplpy cms master_to_ga"
	exit
else
	if [ "$1" == "cms" -a "$2" == "beta_to_beta" ]
	then
		deploy_project cms beta_to_beta
	elif [ "$1" == "cms" -a "$2" == "master_to_beta" ] 
	then
		deploy_project cms master_to_beta
	elif [ "$1" == "cms"  -a "$2" == "master_to_ga" ]
	then
		deploy_project cms master_to_ga
	elif [ "$1" == "file" -a "$2" == "beta_to_beta" ]
	then
		deploy_project file beta_to_beta
	elif [ "$1" == "file" -a "$2" == "master_to_beta" ]
	then
		deploy_project file master_to_beta
	elif [ "$1" == "file" -a "$2" == "master_to_ga" ]
	then
		deploy_project file master_to_ga
	elif [ "$1" == "hotline" -a "$2" == "beta_to_beta" ]
	then
		deploy_project hotline beta_to_beta
	elif [ "$1" == "hotline" -a "$2" == "master_to_beta" ]
        then
                deploy_project hotline master_to_beta
	elif [ "$1" == "hotline" -a "$2" == "master_to_ga" ]
        then
                deploy_project hotline master_to_ga
	elif [ "$1" == "static" -a "$2" == "beta_to_beta" ]
        then
                deploy_project static beta_to_beta
	elif [ "$1" == "static" -a "$2" == "master_to_beta" ]
        then
                deploy_project static master_to_beta
	elif [ "$1" == "static" -a "$2" == "master_to_ga" ]
        then
                deploy_project static master_to_ga
	elif [ "$1" == "index" -a "$2" == "default" ]
        then
                deploy_index_style index
	elif [ "$1" == "crm" -a "$2" == "default" ]
        then
                deploy_index_style crm
	
	elif [ "$1" == "news" -a "$2" == "beta_to_beta" ]
        then
                deploy_project news beta_to_beta
        elif [ "$1" == "news" -a "$2" == "master_to_beta" ]
        then
                deploy_project news master_to_beta
        elif [ "$1" == "news" -a "$2" == "master_to_ga" ]
        then
                deploy_project news master_to_ga
        elif [ "$1" == "sapi" -a "$2" == "beta_to_beta" ]
        then
                deploy_project sapi beta_to_beta
        elif [ "$1" == "sapi" -a "$2" == "master_to_beta" ]
        then
                deploy_project sapi master_to_beta
        elif [ "$1" == "sapi" -a "$2" == "master_to_ga" ]
        then
                deploy_project sapi master_to_ga
	
	else
		echo "there is no project $1"
		exit 1
	fi
fi
